services:
  - type: web
    name: brasa-negra-website
    runtime: node
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: NODE_VERSION
        value: 18
